import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/QueryProvider";
import { Toaster } from "@/components/ui/Toaster";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const inter = Inter({ subsets: ["latin"],   display: 'swap'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body >
          <Providers>
              {children}
            <Toaster />
            <ReactQueryDevtools />
          </Providers>
      </body>
    </html>
  );
}
