import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Providers from "@/providers/QueryProvider";
import { Toaster } from "@/components/ui/Toaster";
import AuthProviders from "@/providers/AuthProvider";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

const inter = Inter({ subsets: ["latin"],   display: 'swap'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body >
        <AuthProviders>
          <Providers>
            <Navbar />
            <Sidebar />
            <div className='container max-w-7xl mx-auto h-full pt-12 '>
              {children}
            </div>
            <Toaster />
            <ReactQueryDevtools />

          </Providers>
        </AuthProviders>
      </body>
    </html>
  );
}
